use var/log dir for logs
onaio/express-server pull request #19
Opened 2021-11-16 10:55 UTC by machariamuguku

- change log directory from /tmp/logs to /var/log
- part of conversation [here](https://github.com/onaio/infrastructure/pull/5107#discussion_r749141676) and changes [here](https://github.com/opensrp/helm-charts/pull/44)

2021-11-16 13:45 UTC, p-netm submitted a review, later dismissed

2021-11-16 13:53 UTC, p-netm requested changes

2021-11-16 13:53 UTC, p-netm commented on src/configs/__mocks__/envs.ts
> +export const EXPRESS_LOGS_FILE_PATH = '/var/log/reveal-express-server.log';
should be `/var/log/express/...`

2021-11-17 08:52 UTC, p-netm approved these changes

2021-11-17 09:21 UTC, KipSigei approved these changes

2021-11-17 09:23 UTC, merged